# .github/workflows/lint_test_ci.yml
# This workflow will install Python dependencies, lint, test, and scan for vulnerabilities

name: Missile Command CI

on:
  workflow_run:
    workflows: ["Python Setup"]
    types:
      - completed
    branches: [ main, dev ]

jobs:
  test-and-scan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        
    - name: Download python environment
      uses: actions/download-artifact@v3
      with:
        name: python-env
        
    - name: Install dependencies
      run: |
        python -m pip install -r installed_packages.txt
    
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Check formatting with Black
      run: black --check .
    
    - name: Type checking with mypy
      run: mypy .
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
    
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
    
    - name: Dependency security check
      run: |
        safety check
        pip-audit
    
    - name: Test with pytest
      run: pytest
    
    - name: Run coverage
      run: |
        pip install pytest-cov
        pytest --cov=. --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}