# .github/workflows/1-python-setup.yml
name: Python Environment Setup

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'requirements.txt'
      - '**.py'
      - '.github/workflows/1-python-setup.yml'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'requirements.txt'
      - '**.py'
      - '.github/workflows/1-python-setup.yml'

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SDL and other dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
                                libfreetype6-dev libportmidi-dev
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel setuptools
        
        # Install pygame separately with specific options
        python -m pip install pygame==2.0.1 --no-cache-dir
        
        # Install remaining requirements
        pip install -r requirements.txt
        pip install flake8 pytest black mypy safety
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-py${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-py${{ matrix.python-version }}-pip-